### ISSUE TITLE
Send notification to specific player ID. How would I do this?!

### ISSUE THREAD

**Issue by holgersindbaek** [SeVeNDuS/node-onesignal-api#1]
This is how my code looks now:

  // Setup options
  var params = {
    app_id: process.env.ONE_SIGNAL_ID,
    contents: { 'en': message }
    data: info
  };

  // Push notification
  onesignal_client.notifications.create(process.env.ONE_SIGNAL_KEY, params, function (err, response) {
    if (err) {
      raygunClient.send(err);
      console.log('Encountered error', err);
    } else {
      console.log(response);
    }
  });

Where can I add the player ID's I want to sent the notification to?

**Comment by SeVeNDuS** [comment]
The params object should have properties specified by one signal in https://documentation.onesignal.com/docs/notifications-create-notification

To send to an specefici player id you need to add the property include_player_ids into the params variable

``` javascript
var params = {
    app_id: process.env.ONE_SIGNAL_ID,
    contents: { 'en': message }
    data: info,
    include_player_ids: [ONESIGNAL_PLAYER_ID]
};
```
