### ISSUE TITLE
Onesignal gathers user data when SDK is used, but is that avoidable using this lib? 

### ISSUE THREAD

**Issue by jasan-s** [SeVeNDuS/node-onesignal-api#6]
When i use javascript sdk on my page to create service worker it has acces to all user data, but will using this lib(server Rest Api) limit what onesignal can collect to just what my notifications contain ?

**Comment by SeVeNDuS** [comment]
That question must be answered by onesignal. This lib is only a wrapper to connect onesignal rest api
